"""Wire runbreaker into each host CLI's hook configuration.

Hooks are spawned as a bare `python3`, with no venv active, so the package has to
be findable without one. `install` resolves the package's absolute location once
and bakes it into a shim script per (provider, event). A `PYTHONPATH=...` prefix
inside the command string would work only if the provider runs commands through a
shell — none of the three promise that.

Existing config files are merged, never clobbered.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from contextlib import suppress
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import runbreaker
from runbreaker import gate
from runbreaker.config import CONFIG_NAME, Config

EVENTS = ("pre_tool_use", "stop")

SHIM_TEMPLATE = '''#!/usr/bin/env python3
"""Generated by `runbreaker install`. Do not edit; re-run install instead."""
import sys

# The import sits inside the guard on purpose. `hook.main` has its own catch-all,
# but it cannot protect the import that reaches it: a deleted venv or a moved
# checkout raises ImportError here and exits 1. Copilot CLI reads any exit code
# other than 0 or 2 as a *deny* and locks the user out of every tool. Exiting 0
# leaves the run unguarded — the lesser failure, and exactly what an uninstalled
# runbreaker would do.
try:
    sys.path.insert(0, {package_root!r})
    from runbreaker.hook import main

    main(["--provider", {provider!r}, "--event", {event!r}])
except SystemExit:
    raise
except BaseException:
    raise SystemExit(0)
'''

CONFIG_TEMPLATE = """# runbreaker — https://github.com/  (see README.md)
# Environment variables (RUNBREAKER_*) override everything here.

[budget]
token_source = "auto"        # follows the provider; or "claude" / "codex" / "null"
recompute_every = 5          # re-read the token file every Nth tool call; 0 disables

[[conditions]]
id = "step_budget"
max_steps = 250              # 0 disables

[[conditions]]
id = "gate_failures"
threshold = 3

# Observe without enforcing while you tune thresholds: conditions and the gate still
# evaluate and audit what they *would* do, but nothing is denied. RUNBREAKER_ENFORCE
# overrides this.
# [breaker]
# mode = "warn"              # or "block" (default)

# Uncomment to bound wall-clock time. Provider-agnostic, like step_budget.
# [[conditions]]
# id = "time_budget"
# max_minutes = 45           # 0 disables

# Uncomment to catch a stuck agent repeating itself: the same tool call (or an
# A-B-A-B cycle) fired threshold times. Matches only identical calls, so ordinary
# edit/test cycles that make progress never trip.
# [[conditions]]
# id = "repeat_loop"
# threshold = 5              # 0 disables

# Uncomment to bound token spend. Abstains when usage cannot be read (e.g. Copilot).
# [[conditions]]
# id = "token_budget"
# max_tokens = 2_000_000
# trip_at_fraction = 0.9     # trip with margin — token ledgers are approximate

# Uncomment to bound estimated dollar spend. A blended-price layer over token_budget;
# coarse by design (one $/1M rate, no input/output split). Abstains on unknown usage.
# [[conditions]]
# id = "cost_budget"
# max_usd = 10
# price_per_mtok = 15

# Codex reports its own rate-limit usage; abstains on other providers.
# [[conditions]]
# id = "rate_limit_pressure"
# max_percent = 80

# The quality gate is entirely config-driven. With no checks it is a no-op.
# [gate]
# watch = ["src/**/*.py"]    # empty => run on every stop
# tail_lines = 40
#
# [[gate.checks]]
# name = "pytest"
# command = ["python3", "-m", "pytest", "-q"]
# timeout = 300
# fail_records_breaker = true
"""


@dataclass(frozen=True)
class Result:
    written: list[Path]
    notes: list[str]


@dataclass(frozen=True)
class Check:
    ok: bool
    label: str
    detail: str = ""


def package_root() -> Path:
    """The directory that must be on sys.path for `import runbreaker` to work."""
    return Path(runbreaker.__file__).resolve().parent.parent


def write_shims(config: Config, providers: tuple[str, ...]) -> list[Path]:
    shim_dir = config.home / "shims"
    shim_dir.mkdir(parents=True, exist_ok=True)
    written = []
    root = str(package_root())
    for provider in providers:
        for event in EVENTS:
            path = shim_dir / f"{provider}_{event}.py"
            path.write_text(
                SHIM_TEMPLATE.format(package_root=root, provider=provider, event=event),
                encoding="utf-8",
            )
            with suppress(OSError):  # no-op on Windows; harmless
                path.chmod(0o755)
            written.append(path)
    return written


def interpreter() -> str:
    """The interpreter to spawn hooks with.

    `sys.executable` — the one running `install` — rather than a bare `python3`.
    Windows has no `python3` on PATH by default, and a hook that fails to start is
    worse than useless: Claude treats the non-zero exit as a harmless error and
    proceeds unguarded, while Copilot CLI reads it as a *deny* and locks the user
    out of every tool.
    """
    return sys.executable or "python3"


def shim_path(config: Config, provider: str, event: str) -> Path:
    return config.home / "shims" / f"{provider}_{event}.py"


def host_config_path(config: Config, provider: str) -> Path:
    """Where each host CLI reads its hook registrations from."""
    return {
        "claude": config.project / ".claude" / "settings.json",
        "codex": config.project / ".codex" / "hooks.json",
        "copilot": config.project / ".github" / "hooks" / "runbreaker.json",
    }[provider]


def _quote(value: str) -> str:
    """Quote a path for a shell command string. Windows paths have spaces."""
    return f'"{value}"' if " " in value else value


PRE_TOOL_TIMEOUT = 30
MIN_STOP_TIMEOUT = 60


def stop_timeout(config: Config) -> int:
    """How long the host must wait for the Stop hook before giving up.

    The gate runs the project's own checks, and a host timeout shorter than they
    take is silent poison: Copilot fails *open* on a timed-out hook, so a slow test
    suite would quietly disable the gate. Size the host's patience from the config.
    """
    if not config.gate.enabled:
        return MIN_STOP_TIMEOUT
    total = sum(check.timeout or gate.DEFAULT_TIMEOUT for check in config.gate.checks)
    return max(MIN_STOP_TIMEOUT, total + PRE_TOOL_TIMEOUT)


def _timeout(config: Config, event: str) -> int:
    return PRE_TOOL_TIMEOUT if event == "pre_tool_use" else stop_timeout(config)


def _exec_entry(config: Config, provider: str, event: str) -> dict[str, Any]:
    """Claude's exec form: the executable and its argv, spawned with no shell.

    No shell means no quoting rules, no `sh -c`, no PowerShell parsing — the only
    host that offers this, and the only place runbreaker can guarantee it.
    `${CLAUDE_PROJECT_DIR}` keeps the shim path out of the committed config, so the
    file survives a different checkout location.
    """
    shim = shim_path(config, provider, event)
    try:
        arg = f"${{CLAUDE_PROJECT_DIR}}/{shim.relative_to(config.project).as_posix()}"
    except ValueError:  # RUNBREAKER_HOME points outside the project
        arg = str(shim)
    return {
        "type": "command",
        "command": interpreter(),
        "args": ["-S", arg],
        "timeout": _timeout(config, event),
    }


def _shell_command(config: Config, provider: str, event: str) -> str:
    """A command string for the hosts that offer no exec form.

    It is a bare interpreter invocation — no pipes, no redirects, no shell builtins,
    nothing that needs a shell to mean anything. The shell is the host's choice, not
    ours; all we hand it is a path and a flag.
    """
    shim = shim_path(config, provider, event)
    return f"{_quote(interpreter())} -S {_quote(str(shim))}"


def _needs_call_operator(config: Config, provider: str, event: str) -> bool:
    """True when a path has a space, so the command string must be quoted.

    PowerShell reads a quoted executable path as a string literal unless it is
    prefixed with the call operator `&` — while bash rejects a leading `&` outright.
    One string cannot satisfy both, so this is the one case where a PowerShell-specific
    override is unavoidable. It is still a bare interpreter invocation, not a script.
    """
    return " " in interpreter() or " " in str(shim_path(config, provider, event))


def _load_json(path: Path) -> dict[str, Any]:
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return loaded if isinstance(loaded, dict) else {}


def _save_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _is_ours(entry: Any) -> bool:
    """Only an entry pointing at our shim directory is ours to replace.

    Matching on the word "runbreaker" alone would clobber a user's own hook that
    merely mentions us.
    """
    blob = json.dumps(entry)
    return "runbreaker" in blob and "shims" in blob


def _append_once(entries: list[Any], entry: dict[str, Any]) -> None:
    for i, existing in enumerate(entries):
        if _is_ours(existing):
            entries[i] = entry
            return
    entries.append(entry)


def _install_claude(config: Config) -> Path:
    path = host_config_path(config, "claude")
    data = _load_json(path)
    hooks = data.setdefault("hooks", {})

    # A single `*` registration: the budget must count reads too, and the handler
    # already knows which tools mutate. Registering write tools separately would
    # spawn a second interpreter on every Write.
    _append_once(
        hooks.setdefault("PreToolUse", []),
        {"matcher": "*", "hooks": [_exec_entry(config, "claude", "pre_tool_use")]},
    )
    for event in ("Stop", "SubagentStop"):
        _append_once(
            hooks.setdefault(event, []),
            {"hooks": [_exec_entry(config, "claude", "stop")]},
        )
    _save_json(path, data)
    return path


def _codex_entry(config: Config, event: str) -> dict[str, Any]:
    # Codex has no exec form, so `command` is a string it hands to a shell. The
    # string is a bare interpreter invocation; the same one works on both platforms,
    # so no `commandWindows` override is needed.
    return {
        "type": "command",
        "command": _shell_command(config, "codex", event),
        "timeout": _timeout(config, event),
    }


def _install_codex(config: Config) -> Path:
    path = host_config_path(config, "codex")
    data = _load_json(path)
    hooks = data.setdefault("hooks", {})
    _append_once(
        hooks.setdefault("PreToolUse", []),
        {"matcher": ".*", "hooks": [_codex_entry(config, "pre_tool_use")]},
    )
    _append_once(
        hooks.setdefault("Stop", []),
        {"hooks": [_codex_entry(config, "stop")]},
    )
    _save_json(path, data)
    return path


def _install_copilot(config: Config) -> Path:
    path = host_config_path(config, "copilot")
    data = _load_json(path)
    data.setdefault("version", 1)
    hooks = data.setdefault("hooks", {})
    # PascalCase event names make Copilot emit VS Code-compatible snake_case
    # payloads, identical in shape to Claude's.
    #
    # `command` is Copilot's shell-neutral field: it is copied to both `bash` and
    # `powershell` when neither is given. We never write a `bash` key. The lone
    # exception is a path with a space, where the two shells' quoting rules cannot
    # be satisfied by one string — see `_needs_call_operator`.
    for event in ("PreToolUse", "Stop"):
        name = "pre_tool_use" if event == "PreToolUse" else "stop"
        command = _shell_command(config, "copilot", name)
        entry: dict[str, Any] = {
            "type": "command",
            "timeoutSec": _timeout(config, name),
            "command": command,
        }
        if _needs_call_operator(config, "copilot", name):
            entry["powershell"] = f"& {command}"
        _append_once(hooks.setdefault(event, []), entry)
    _save_json(path, data)
    return path


def _codex_notes() -> list[str]:
    notes = [
        "codex: hooks may need `[features] hooks = true` in ~/.codex/config.toml on some builds.",
    ]
    binary = shutil.which("codex")
    version = ""
    if binary:
        try:
            version = subprocess.check_output(
                [binary, "--version"], text=True, stderr=subprocess.DEVNULL, timeout=10
            ).strip()
        except (OSError, subprocess.SubprocessError):
            version = ""
    notes.append(
        "codex: `apply_patch` only fires PreToolUse since openai/codex#18391 (after v0.118). "
        "On older builds only Bash is gated and file edits slip past. "
        f"Detected: {version or 'unknown'}."
    )
    return notes


def _ensure_gitignore(config: Config) -> None:
    path = config.project / ".gitignore"
    wanted = (".runbreaker/state/", ".runbreaker/shims/")
    try:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
    except OSError:
        return
    missing = [line for line in wanted if line not in current]
    if not missing:
        return
    with path.open("a", encoding="utf-8") as fh:
        if current and not current.endswith("\n"):
            fh.write("\n")
        fh.writelines(f"{line}\n" for line in missing)


INSTALLERS = {
    "claude": _install_claude,
    "codex": _install_codex,
    "copilot": _install_copilot,
}


def scaffold_config(config: Config) -> Path | None:
    """Write a starter runbreaker.toml, once. Never overwrites a tuned one."""
    path = config.home / CONFIG_NAME
    if path.exists():
        return None
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(CONFIG_TEMPLATE, encoding="utf-8")
    return path


def diagnose(config: Config, providers: tuple[str, ...]) -> list[Check]:
    """Verify each provider is actually wired up, without changing anything.

    Turns the install-time footguns the README documents (missing shim, hook never
    registered, stale Codex build) into a checklist a human can read at a glance.
    """
    checks: list[Check] = []
    for provider in providers:
        if provider not in INSTALLERS:
            checks.append(Check(False, f"{provider}: unknown provider"))
            continue

        for event in EVENTS:
            shim = shim_path(config, provider, event)
            checks.append(
                Check(
                    shim.is_file(),
                    f"{provider}: shim {event}",
                    str(shim)
                    if shim.is_file()
                    else f"missing — run `runbreaker install --provider {provider}`",
                )
            )

        cfg_path = host_config_path(config, provider)
        registered = _is_ours(_load_json(cfg_path))
        checks.append(
            Check(
                registered,
                f"{provider}: hook registered",
                str(cfg_path)
                if registered
                else f"no runbreaker entry in {cfg_path} — run `runbreaker install`",
            )
        )

    if "codex" in providers:
        checks.extend(Check(True, "codex: note", note) for note in _codex_notes())
    return checks


def install(config: Config, providers: tuple[str, ...]) -> Result:
    written = write_shims(config, providers)
    scaffolded = scaffold_config(config)
    if scaffolded is not None:
        written.append(scaffolded)
    notes: list[str] = []
    for provider in providers:
        installer = INSTALLERS.get(provider)
        if installer is None:
            notes.append(f"unknown provider: {provider}")
            continue
        written.append(installer(config))

    if "codex" in providers:
        notes.extend(_codex_notes())
    if "copilot" in providers:
        notes.append(
            "copilot: token usage is not exposed to hooks (github/copilot-cli#2947), "
            "so only `step_budget` applies there."
        )
    notes.append(
        "vscode: Copilot agent mode in VS Code reads .claude/settings.json and "
        ".github/hooks/*.json, so it is covered by the files above — no separate install. "
        "Its `copilot_*` tool names route to the vscode adapter automatically."
    )
    notes.append(
        "all: runbreaker ships no shell scripts. Claude gets an exec-form hook (no shell "
        "at all); Codex and Copilot accept only a command string, which we keep to a bare "
        "interpreter invocation."
    )
    notes.append(
        "all: Bash is intentionally not blocked, so `runbreaker reset` stays reachable. "
        "This is a brake against runaway loops, not a security boundary."
    )

    _ensure_gitignore(config)
    return Result(written=written, notes=notes)
